### ISSUE TITLE
[question] what's your sampling strategy?

### ISSUE THREAD

**Issue by GrayXu** [twitter/cache-trace#3]
A great work!   
But I found the timestamps of the last queries in different clusters are different. So I'm wondering what's your sampling strategy?

Thanks!

**Comment by 1a1a11a** [comment]
Hi Gary, 
    Great question! The trace is collected from one node (container) of each cluster, there is no sampling on the trace collection, but the objects are sharded between nodes. I am not sure why the end time is different, can you show me which ones are different? The collection stoppped at the same time, they should have close by end time.

**Comment by GrayXu** [comment]
Sorry for misleading you...  
I mean how to sample the data of `samples/2020Mar`. It just seems like greping 1m data from the top?

**Comment by 1a1a11a** [comment]
Yes, the samples were just first 1 million requests. Because different nodes (clusters) have different request rates, they have different end time.

**Comment by GrayXu** [comment]
> Yes, the samples were just first 1 million requests. Because different nodes (clusters) have different request rates, they have different end time.

Thanks again!  
I wrongly treat it as uniform sampling, because it's kindof default strategy.   
But it make sense, since such smaller dataset can't represent the original.
