### ISSUE TITLE
Uncompressed trace files 

### ISSUE THREAD

**Issue by Yiling-J** [twitter/cache-trace#9]
Is it possible to put the uncompressed trace files on ftp.pdl.cmu.edu or other places? In this way i can use range http header to download part of the file and send to cache. For example the meta KV trace, I can use `curl -v -r 0-5000 'https://cachelib-workload-sharing.s3-us-west-2.amazonaws.com/pub/kvcache/202206/kvcache_traces_1.csv'` to get first 5000 bytes.

**Comment by 1a1a11a** [comment]
Because of the size of the traces, it is not possible to have all traces decompressed, but I have added (the most important) one here https://ftp.pdl.cmu.edu/pub/datasets/twemcacheWorkload/open_source/cluster52.sort
